/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.symmetry.calculator.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Equ service. Represents a row in the &quot;dupa_Equ&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.symmetry.calculator.model.impl.EquModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.symmetry.calculator.model.impl.EquImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Equ
 * @see com.symmetry.calculator.model.impl.EquImpl
 * @see com.symmetry.calculator.model.impl.EquModelImpl
 * @generated
 */
@ProviderType
public interface EquModel extends BaseModel<Equ>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a equ model instance should use the {@link Equ} interface instead.
	 */

	/**
	 * Returns the primary key of this equ.
	 *
	 * @return the primary key of this equ
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this equ.
	 *
	 * @param primaryKey the primary key of this equ
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this equ.
	 *
	 * @return the uuid of this equ
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this equ.
	 *
	 * @param uuid the uuid of this equ
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the equ ID of this equ.
	 *
	 * @return the equ ID of this equ
	 */
	public long getEquId();

	/**
	 * Sets the equ ID of this equ.
	 *
	 * @param equId the equ ID of this equ
	 */
	public void setEquId(long equId);

	/**
	 * Returns the group ID of this equ.
	 *
	 * @return the group ID of this equ
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this equ.
	 *
	 * @param groupId the group ID of this equ
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this equ.
	 *
	 * @return the company ID of this equ
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this equ.
	 *
	 * @param companyId the company ID of this equ
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this equ.
	 *
	 * @return the user ID of this equ
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this equ.
	 *
	 * @param userId the user ID of this equ
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this equ.
	 *
	 * @return the user uuid of this equ
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this equ.
	 *
	 * @param userUuid the user uuid of this equ
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this equ.
	 *
	 * @return the user name of this equ
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this equ.
	 *
	 * @param userName the user name of this equ
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this equ.
	 *
	 * @return the create date of this equ
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this equ.
	 *
	 * @param createDate the create date of this equ
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this equ.
	 *
	 * @return the modified date of this equ
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this equ.
	 *
	 * @param modifiedDate the modified date of this equ
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this equ.
	 *
	 * @return the name of this equ
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this equ.
	 *
	 * @param name the name of this equ
	 */
	public void setName(String name);

	/**
	 * Returns the number1 of this equ.
	 *
	 * @return the number1 of this equ
	 */
	public long getNumber1();

	/**
	 * Sets the number1 of this equ.
	 *
	 * @param number1 the number1 of this equ
	 */
	public void setNumber1(long number1);

	/**
	 * Returns the number2 of this equ.
	 *
	 * @return the number2 of this equ
	 */
	public long getNumber2();

	/**
	 * Sets the number2 of this equ.
	 *
	 * @param number2 the number2 of this equ
	 */
	public void setNumber2(long number2);

	/**
	 * Returns the result of this equ.
	 *
	 * @return the result of this equ
	 */
	public long getResult();

	/**
	 * Sets the result of this equ.
	 *
	 * @param result the result of this equ
	 */
	public void setResult(long result);

	/**
	 * Returns the type of equation of this equ.
	 *
	 * @return the type of equation of this equ
	 */
	@AutoEscape
	public String getTypeOfEquation();

	/**
	 * Sets the type of equation of this equ.
	 *
	 * @param typeOfEquation the type of equation of this equ
	 */
	public void setTypeOfEquation(String typeOfEquation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Equ equ);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Equ> toCacheModel();

	@Override
	public Equ toEscapedModel();

	@Override
	public Equ toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}